artifact_location: file:///home/naradaw/dev/Charles_Schwab/code/RnD/v3/mlflow_experiments/168050635922118841
creation_time: 1730954894954
experiment_id: '168050635922118841'
last_update_time: 1730954894954
lifecycle_stage: active
name: /portfolio-contructor-v3
