artifact_uri: file:///home/naradaw/dev/Charles_Schwab/code/RnD/v3/mlflow_experiments/168050635922118841/8efebbecc1964f37b3a5158c0e67417e/artifacts
end_time: null
entry_point_name: ''
experiment_id: '168050635922118841'
lifecycle_stage: active
run_id: 8efebbecc1964f37b3a5158c0e67417e
run_name: beautiful-bass-739
run_uuid: 8efebbecc1964f37b3a5158c0e67417e
source_name: ''
source_type: 4
source_version: ''
start_time: 1731061812218
status: 1
tags: []
user_id: naradaw
