artifact_uri: file:///home/naradaw/dev/Charles_Schwab/code/RnD/v3/mlflow_experiments/168050635922118841/f2f84132216f4be9bbe14aa5b3d59db3/artifacts
end_time: null
entry_point_name: ''
experiment_id: '168050635922118841'
lifecycle_stage: active
run_id: f2f84132216f4be9bbe14aa5b3d59db3
run_name: worried-bear-344
run_uuid: f2f84132216f4be9bbe14aa5b3d59db3
source_name: ''
source_type: 4
source_version: ''
start_time: 1730954929474
status: 1
tags: []
user_id: naradaw
