artifact_uri: file:///home/naradaw/dev/Charles_Schwab/code/RnD/v3/mlflow_experiments/168050635922118841/6d4ee72ffeb24e5b84ba4304e541827b/artifacts
end_time: null
entry_point_name: ''
experiment_id: '168050635922118841'
lifecycle_stage: active
run_id: 6d4ee72ffeb24e5b84ba4304e541827b
run_name: adaptable-ray-637
run_uuid: 6d4ee72ffeb24e5b84ba4304e541827b
source_name: ''
source_type: 4
source_version: ''
start_time: 1731061945002
status: 1
tags: []
user_id: naradaw
