artifact_uri: file:///home/naradaw/dev/Charles_Schwab/code/RnD/v3/mlflow_experiments/168050635922118841/4acb5b95747f406fbd0b40672dcffdf1/artifacts
end_time: null
entry_point_name: ''
experiment_id: '168050635922118841'
lifecycle_stage: active
run_id: 4acb5b95747f406fbd0b40672dcffdf1
run_name: skittish-gnu-47
run_uuid: 4acb5b95747f406fbd0b40672dcffdf1
source_name: ''
source_type: 4
source_version: ''
start_time: 1730967464852
status: 1
tags: []
user_id: naradaw
