artifact_location: file:///home/naradaw/dev/Charles_Schwab/code/RnD/v5/mlflow_experiments/406802491392147758
creation_time: 1732179855509
experiment_id: '406802491392147758'
last_update_time: 1732179855509
lifecycle_stage: active
name: /portfolio-contructor-v5-information_ratio
