artifact_location: file:///home/naradaw/dev/Charles_Schwab/code/RnD/v4/mlflow_experiments/589106785306301247
creation_time: 1731319215217
experiment_id: '589106785306301247'
last_update_time: 1731319215217
lifecycle_stage: active
name: /portfolio-contructor-v4
