artifact_location: file:///home/naradaw/dev/Charles_Schwab/code/RnD/v2/mlflow_experiments/930648686917041142
creation_time: 1730715551772
experiment_id: '930648686917041142'
last_update_time: 1730715551772
lifecycle_stage: active
name: /portfolio-contructor-v2
