artifact_location: file:///home/naradaw/dev/Charles_Schwab/code/RnD/v5/mlflow_experiments/622240344876609488
creation_time: 1732163408797
experiment_id: '622240344876609488'
last_update_time: 1732163408797
lifecycle_stage: active
name: /portfolio-contructor-v5
