artifact_uri: file:///home/naradaw/dev/Charles_Schwab/code/RnD/v3/mlflow_experiments/168050635922118841/84ef1fb55a9641dc9d8eb57ae569d9e3/artifacts
end_time: null
entry_point_name: ''
experiment_id: '168050635922118841'
lifecycle_stage: active
run_id: 84ef1fb55a9641dc9d8eb57ae569d9e3
run_name: blushing-vole-166
run_uuid: 84ef1fb55a9641dc9d8eb57ae569d9e3
source_name: ''
source_type: 4
source_version: ''
start_time: 1730960189543
status: 1
tags: []
user_id: naradaw
