artifact_location: file:///home/naradaw/dev/Charles_Schwab/code/RnD/v4/mlflow_experiments/0
creation_time: 1731319215202
experiment_id: '0'
last_update_time: 1731319215202
lifecycle_stage: active
name: Default
