artifact_location: file:///home/naradaw/dev/Charles_Schwab/code/RnD/v3/mlflow_experiments/0
creation_time: 1730954894947
experiment_id: '0'
last_update_time: 1730954894947
lifecycle_stage: active
name: Default
