artifact_uri: file:///home/naradaw/dev/Charles_Schwab/code/RnD/v3/mlflow_experiments/168050635922118841/7370e042ab224bf5aeee66ba7ad14f60/artifacts
end_time: null
entry_point_name: ''
experiment_id: '168050635922118841'
lifecycle_stage: active
run_id: 7370e042ab224bf5aeee66ba7ad14f60
run_name: colorful-cub-410
run_uuid: 7370e042ab224bf5aeee66ba7ad14f60
source_name: ''
source_type: 4
source_version: ''
start_time: 1730968205406
status: 1
tags: []
user_id: naradaw
