artifact_location: file:///home/naradaw/dev/Charles_Schwab/code/RnD/v2/mlflow_experiments/761903683111437854
creation_time: 1730803455740
experiment_id: '761903683111437854'
last_update_time: 1730803455740
lifecycle_stage: active
name: /portfolio-contructor-v3
